### ISSUE TITLE
[User Story]: View all posts

### ISSUE THREAD

**Issue by alexkisielewicz** [alexkisielewicz/photo-adventures#1]
# User story: 
As **Site User**, I can **view a list of all posts** so that **I can select one to read**

# Acceptance criteria:
- [x] Posts retrieved from database are visible on the website
- [x] There are at least two posts visible

# Tasks
- [x] Create post model
- [x] Create a database
- [x] Make migration
