### ISSUE TITLE
[User Story] Basic page template

### ISSUE THREAD

**Issue by alexkisielewicz** [alexkisielewicz/photo-adventures#17]
# User story: 
As **Site User**, I can **view page content** so that **I can browse the website and interact with the content**

# Tasks
- [x] Create basic html sceleton and add semantic tags
- [x] Add headers including links to style, bootstrap
- [x] Add basic navigation
- [x] Add script links to bootstrap js and jquery
