### ISSUE TITLE
[User Story] Prevent user from liking own posts

### ISSUE THREAD

**Issue by alexkisielewicz** [alexkisielewicz/photo-adventures#23]
# User story: 
As **Site Admin**, I can **prevent users from liking their own posts** so that **posts can be liked only by other users**

# Acceptance criteria:
- User can not add like to own pows
- Feedback is displayed

# Tasks
- [ ] Add if else statement to check if the active user is the author of the post
- [ ] Disable likes form if the statement above is true/allow to like if not true
- [ ] Add user feedback in html template

**Comment by alexkisielewicz** [comment]
Additionally, Django messages have been implemented in later stage to handle messages - when like is added and removed
