### ISSUE TITLE
[User Story] Manage posts

### ISSUE THREAD

**Issue by alexkisielewicz** [alexkisielewicz/photo-adventures#3]
# User story: 
As **Site Admin**, I can **manage posts** so that **receive_benefit**

# Acceptance criteria:
- [ ] Admin can perform CRUD operations on posts

# Tasks
- [ ] add class PostAdmin
- [ ] add class CommentAdmin
