### ISSUE TITLE
[User Story] Share posts on social media

### ISSUE THREAD

**Issue by alexkisielewicz** [alexkisielewicz/photo-adventures#37]
# User story: 
As **Site User**, I can **share interesting posts on popular social media platforms** so that **my friends can learn about posts that I enjoyed reading**

# Tasks
- [x] In the full post template - add a button that the user can click to share a post on social media
- [x] Provide Facebook and Twitter sharing buttons as they are the most popular platforms. 
- [x] Add to the template open graph meta tags that are widely used by social platforms to read meta tags of sharing content.
