### ISSUE TITLE
[User Story] Open blog post

### ISSUE THREAD

**Issue by alexkisielewicz** [alexkisielewicz/photo-adventures#5]
# User story: 
As **Site User**, I can **select a post** so that **I can read it**

# Acceptance criteria:
- [x] Post is displayed on the website
- [x] User can click a link leading to the post
- [x] User can read full post 

# Tasks
- [x] Add a link to the post in the template
- [x] Add post to the views
